import React from "react";
import '../Cables/Cables.css';
import rectlogo from '../../Accets/cable background.png';

const Cables = () => {
    const productscables = [
        "PVC insulated Sheathed/ Unsheathed Single Core/ Multi Core Cables as per IS : 694/ 1990",
        "KALINGA PREMIUM PVC INSULATED SINGLE/MULTICORE PVC SHEATHED CABLES CONFORMING TO IS 194- 1990",
        "KALINGA PREMIUM COPPER CONDUCTOR PVC INSULATED UNSEATHERED FLEXIBLE WIRES & CORDS FOR PANELS & FLEXIBLE WIRING CONFORMING TO IS: 694-1990",
        "KALINGA PREMIUM COPPER CONDUCTOR PVC INSULATED UNSEATHERED HOUSE & INDUSTRIAL WIRES CONFORMING TO IS: 694- 1990",
        "KALINGA PREMIUM COPPER CONDUCTOR PVC INSULATED SINGLE/MULTICORE PVC SHEATHERED CABLES CONFORMING TO IS 694- 1990",
        "KALINGA PREMIUM COPPER CONDUCTOR PVC INSULATED UNSEATHERED MULTISTRAND WIRES FOR HOUSE & INDUSTRIAL WIRING CONFORMING TO IS: 694- 1990",
        "KALINGA PREMIUM COPPER CONDUCTOR PVC SEATHERED 3CORE SUBMERSIBLE FLAT WITH ANNEALED BEAR MULTISTANDED COPPER CONDUCTOR SUITABLE FOR 650/110 VOLTS",
        "KALINGA PREMIUM PVC INSULATED AND PVC SHEATHED ARMORED/ UNARMORED SINGLE CORE/ MULTI CORE CABLES AS PER IS 1554 PART- 1)- 1988",
        "KALINGA PREMIUM SINGLE CORE PVC INSULATED AND PVC SHEATHED ARMORED/ UNARMORED POWER CABLES WITH ALUMINIUM CONDUCTOR SUITABLE FOR 1100 VOLTS.",
        "KALINGA PREMIUM TWO CORE PVC INSULATED AND PVC SHEATHED ARMORED/ UNARMORED POWER CABLES WITH ALUMINIUM COPPER CONDUCTOR SUITABLE FOR 1100 VOLTS.",
        "KALINGA PREMIUM THREE CORE PVC INSULATED AND PVC SHEATHED ARMORED/ UNARMORED POWER CABLES WITH ALUMINIUM COPPER CONDUCTOR SUITABLE FOR 1100 VOLTS.",
        "KALINGA PREMIUM THREE & HALF CORE PVC INSULATED AND PVC SHEATHED ARMORED/ UNARMORED POWER CABLES WITH ALUMINIUM COPPER CONDUCTOR SUITABLE FOR 1100 VOLTS.",
        "KALINGA PREMIUM FOUR CORE PVC INSULATED AND PVC SHEATHED ARMORED/ UNARMORED POWER CABLES WITH ALUMINIUM COPPER CONDUCTOR SUITABLE FOR 1100 VOLTS.",
        "KALINGA PREMIUM PVC INSULATED ARMORED/ UNARMORED WITH COPPER CONDUCTOR SUITABLE FOR 1100 VOLTS.",
        "KALINGA PREMIUM 1.1 kV SINGLE CORE XPLE INSULATED UNARMORED AND ARMORED CABLES WITH ALUMINIUM/ COPPER CONDUCTOR TO IS 7098 (PART-1)- 1988",
        "KALINGA PREMIUM 1.1 kV TWO CORE XPLE INSULATED UNARMORED AND ARMORED CABLES WITH ALUMINIUM/ COPPER CONDUCTOR TO IS 7098 (PART-1)- 1988",
        "KALINGA PREMIUM 1.1 kV THREE CORE XPLE INSULATED UNARMORED AND ARMORED CABLES WITH ALUMINIUM/ COPPER CONDUCTOR TO IS 7098 (PART-1)- 1988",
        "KALINGA PREMIUM 1.1 kV THREE & HALF CORE XPLE INSULATED UNARMORED AND ARMORED CABLES WITH ALUMINIUM/ COPPER CONDUCTOR TO IS 7098 (PART-1)- 1988",
        "KALINGA PREMIUM 1.1 kV FOUR CORE XPLE INSULATED UNARMORED AND ARMORED CABLES WITH ALUMINIUM/ COPPER CONDUCTOR TO IS 7098 (PART-1)- 1988",
        "KALINGA PREMIUM XPLE INSULATED UNARMORED/ ARMORED CABLES WITH COPPER CONDUCTOR TO IS 7098 (PART-1)- 1988",
    ];
    return (
        <>
            <div className="cables-background">
                <div className="cables-background-text">
                    <h1>Cables</h1>
                    <h3>Engineered for durability, our cables ensure smooth power transmission and connectivity, making them ideal for residential and industrial use.</h3>
                </div>
            </div>
            <div className="product-list">
                <h2 className="product-heading">Our Products</h2>
                <ul className="product-items">
                    {productscables.map((product, index) => (
                        <li key={index} className="product-item">
                            <span>▶</span> {product}
                        </li>
                    ))}
                </ul>
            </div>
        </>
    )
}
export default Cables;